### ISSUE TITLE
shared task folder

### ISSUE THREAD

**Issue by kohlhaas1808** [evrenvarol/outlook-taskboard#1]
Hi evrenvarol,

I like your kanban System for Outlook. it is a great idea!
What I'm trying to do is to share a task folder with my colleges and show it in the kanban view. 
The problem is, that the person who receive the task folder can not show it in the kanban view, because it didn't find the shared folder. 
In the folder settings is no path where the shared folder could be. 
Do you have a solution for that?

I'm looking forward to your answer.

Best Greetings
Michael

**Comment by evrenvarol** [comment]
Thanks Michael, I'm not using any shared task folders with my colleagues but I think there seems to be solution for that.  

I will update the code and let you know when it is ready for testing. 

Evren

**Comment by kohlhaas1808** [comment]
Hi Evren,
I would really appreciate that! Thank you!

Michael

**Comment by kohlhaas1808** [comment]
I have found a solution for our problem. Now we are using a shared email account.
To get the tasks this function is needed:
`var myRecipient = outlookNS.CreateRecipient(addressName);`
 `myRecipient.Resolve;`
`if(myRecipient.Resolved){`
`var tasks = outlookNS.GetSharedDefaultFolder(myRecipient,13);`
`}`

**Comment by ghost** [comment]
Where should that function be added?

**Comment by kohlhaas1808** [comment]
inside app.js.
it depends on which folder/tasks you need, but for example on every line like this:
`var tasksfolder = outlookNS.GetDefaultFolder(13)`

**Comment by evrenvarol** [comment]
Hi @kohlhaas1808, 
I have done some updates to the master repo, can you please download it again and edit the config.js file for your shared folder setup.

You can change the `Name` value for the name of the folder and the `Owner` value for the owner's name. (whoever is sharing the folder)

Unfortunately, I wasn't able to test it as i don't have any shared folders. In theory, it should work.  Let me know how it goes. Thanks!

**Comment by kohlhaas1808** [comment]
Hey Evren, 
I have found a minor mistake on Line 116 in app.js
`var folder = outlookNS.GetSharedDefaultFolder(recipient, 13).Folders(path);`
you need to change **path** to **folderpath**
After that change the code is working

**Comment by evrenvarol** [comment]
Thanks a lot Michael, I have corrected the line with the current update (several other items fixed as well).

I will be closing this issue as the issue seems to be resolved.
