### ISSUE TITLE
Drag and Drop is not working in Outlook 2016 

### ISSUE THREAD

**Issue by rlodhiya** [evrenvarol/outlook-taskboard#10]
I have followed your basic set up guide and after that I have setup it correctly but still it is not working. Specially when I tried to move task from  one lane to another, it does not do anything. 

Can anyone give me idea how do I solve this?
![error with drag and drop](https://cloud.githubusercontent.com/assets/14235867/20171423/7776bbbc-a728-11e6-940d-ef9f9cd18fd5.PNG)

**Comment by rlodhiya** [comment]
Sort out. Apperantly, when I created folders it came with (this computer only) at the trailing name, I corrected the error and now it is fixed. Thanks.

**Comment by Demian87** [comment]
> trailing name

@rlodhiya , What do you mean? I have this problem too.

UPD. Solved by moving folders to the root folder

**Comment by ParoTheParrot** [comment]
> Sort out. Apperantly, when I created folders it came with (this computer only) at the trailing name, I corrected the error and now it is fixed. Thanks.
@rlodhiya : I don't understand your solution. Do you have advice?

**Comment by ParoTheParrot** [comment]
> UPD. Solved by moving folders to the root folder
@Demian87 : Please explain your solution in detail, thanks!
