### ISSUE TITLE
Descending order not practical when sorting by Date

### ISSUE THREAD

**Issue by GrimmiMeloni** [evrenvarol/outlook-taskboard#11]
Just did an update, and saw the new(?) sort feature.
I would like to sort most of the taskboard by date to have items with a due date stay on top of the lanes.
This also works, but unfortunately the sorting is in descending order. I guess this is due to the fact that when sorting by "importance" this makes sense.

I would like to suggest to either set the sort order for "Date" to ascending. For me personally setting this order for Date as fixed would be sufficient, as I cannot think of a usecase where I would like to see the least pressing things on top. However on alternative could be to make the order for each sort key configurable.

**Comment by GrimmiMeloni** [comment]
I am working on this. Will provide a pull request.

**Comment by evrenvarol** [comment]
Sort option wasn't documented as I wasn't happy with the behaviour of the sort function in Outlook API ..  I was thinking to do same javascript/array sorting, but you were quicker.. thanks 👍
