### ISSUE TITLE
Colored indicator of categories

### ISSUE THREAD

**Issue by FireFighter1017** [evrenvarol/outlook-taskboard#13]
It would be cool to have categories in a colored box based on the category color that's being set in Outlook client.

**Comment by GrimmiMeloni** [comment]
By "categories", do you mean the lanes (Backlog, Next, In Progress, ...), or do you mean the actual Kanban "cards" that are representing individual tasks?

**Comment by evrenvarol** [comment]
I believe he means changing colour of each card/task based on the category colour in Outlook. Currently cards are coloured based on their priority. (high/medium/low). I'm looking to change the overall design of the task lanes and cards. Hopefully I can accommodate both priority indicator and category colours on same card.

**Comment by Shrekmachine** [comment]
The design is slim and perfect. Saying that, coloring the tags based on Outlook categories would be great. Please not coloring the whole card, only the tag

**Comment by BillyMcSkintos** [comment]
I often use more than one category so the tag glyph would need to be added per category and colored or, similar to trello.com, a small line/box colored appropriately.

**Comment by Muehlethaler** [comment]
Have somebody found a posibility for coloring the Standard categories from Outlook?
I hope for a positiv Answer.
Best Regards Raphael

**Comment by BillyMcSkintos** [comment]
JanVV has forked it and implemented colored categories and more:
https://github.com/janvv/outlook-taskboard
