### ISSUE TITLE
Drag and Drop missing / not working

### ISSUE THREAD

**Issue by GrimmiMeloni** [evrenvarol/outlook-taskboard#2]
Is it possible to drag and drop items from one lane to the next?

**Comment by kohlhaas1808** [comment]
check the task folder names and the positions of it. 
You need all the folders like in the instruction.

**Comment by GrimmiMeloni** [comment]
Double checked it. Does not change anything.
Is it in general an expected feature, i.e. the drag'n'drop to work in outlook?

**Comment by kohlhaas1808** [comment]
for me it works like a charm.
please note that the folder "Tasks" is your default task folder. you do not need to create it

**Comment by GrimmiMeloni** [comment]
Well the interesting part is, that dragging inside a lane works (i.e. moving tasks up and down). Lane Changing however does not do anything. 

I would like to dig a bit deeper. I am also somewhat experienced with JS. However I lack the experience of debugging javascript inside outlook. Is there any hidden shortcut or similar, that I can use to pull up a JS console or anything similar in Outlook? If not, what options are there to further chase this?

**Comment by kohlhaas1808** [comment]
You can use IE, just press F12 to debug.

**Comment by GrimmiMeloni** [comment]
OK, after lots of fiddling (that Local Zone LockDown in IE is a real pain) - i managed to get the IE version running.

Good news is, I found the issue. The Documentation lacks showing the Completed folder. Once I added that as a Subfolder next to "InProgress, etc etc" the dragging worked in both IE and Outlook. Maybe the default configuration in config.js is not matching documentation...?

**Comment by kohlhaas1808** [comment]
your're right, the completed folder is missing in the documentation.

**Comment by evrenvarol** [comment]
Apologies for the missing instructions. I was caught by adding some new features in the repo but missed to update the instructions. Instructions are now updated along with the repo (and some new features).

If you really want to open the view in IE, you should use the `kanban-ie.html` file as it contains following line at the header:
`<!-- saved from url=(0016)http://localhost -->`

This tells IE to open the page in Local Intranet Zone = [https://msdn.microsoft.com/en-us/library/ms537628(v=vs.85).aspx](url)

I'm closing the issue assuming you are OK now.
