### ISSUE TITLE
IE error

### ISSUE THREAD

**Issue by ghost** [evrenvarol/outlook-taskboard#4]
I get the attached view when opened in IE 11. I have made the security settings as described. 

One other question is it possible to change which lanes/columns you want in outlook?

![capture](https://cloud.githubusercontent.com/assets/22794016/19342669/08674c92-9133-11e6-904f-078986e4edc0.PNG)

**Comment by evrenvarol** [comment]
hi @mobaraksaid , i have just done some updates on the repo. Can you please re-download it again and use the kanban-ie.html to view the board in IE. 

Please check new instructions (hope they are clearer now) for task folder customisation. You can change the names and titles of those folders with the current release.

**Comment by ghost** [comment]
Hi @evrenvarol  thanks for taken the your time to look at it. I really appreciate that.

The view is more correct now, but no tasks are shown
![capture](https://cloud.githubusercontent.com/assets/22794016/19347451/274d7a30-9149-11e6-90db-9cc5f955e290.PNG)

**Comment by evrenvarol** [comment]
Good, we are getting there. Did you have any custom folder setup? Do you have all subfolders created ? (InProgress, Next, Focus, Waiting and Completed)

**Comment by ghost** [comment]
Yes i have all task folders 
This works in outlook.

![capture](https://cloud.githubusercontent.com/assets/22794016/19347654/34ffc95c-914a-11e6-95c9-d2c34974117d.PNG)

**Comment by evrenvarol** [comment]
And did you enable the IE -> Local Intranet Zone -> "Initialize and script ActiveX controls not marked as safe for scripting" option? 

It looks like either scripting is getting blocked or there is something wrong with the folder setup.

You can press F12 in IE to open up the IE Dev Tools and refresh the window to check if there are any errors in Console tab.

**Comment by ghost** [comment]
This error is shown in the console.

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
kanban-ie.html
HTML1300: Navigation occurred.
kanban-ie.html
Error: Automation server can't create object
   {
      [functions]: ,
      **proto**: { },
      description: "Automation server can't create object",
      message: "Automation server can't create object",
      name: "Error",
      number: -2146827859,
      stack: "Error: Automation server can't create object
   at Global code (file:///C:/Users/MOSAI/OneDrive%20-%20H%20&%20M%20HENNES%20&%20MAURITZ%20AB/1.WORK/Shortcuts/Knowledge/Office%20365/Outlook/Kanban%20board/js/app.js:13:13)"
   }

TypeError: Unable to get property 'GetDefaultFolder' of undefined or null reference
   at getOutlookFolder (file:///C:/Users/MOSAI/OneDrive%20-%20H%20&%20M%20HENNES%20&%20MAURITZ%20AB/1.WORK/Shortcuts/Knowledge/Office%20365/Outlook/Kanban%20board/js/app.js:105:13)
   at getTasksFromOutlook (file:///C:/Users/MOSAI/OneDrive%20-%20H%20&%20M%20HENNES%20&%20MAURITZ%20AB/1.WORK/Shortcuts/Knowledge/Office%20365/Outlook/Kanban%20board/js/app.js:130:13)
   at $scope.init (file:///C:/Users/MOSAI/OneDrive%20-%20H%20&%20M%20HENNES%20&%20MAURITZ%20AB/1.WORK/Shortcuts/Knowledge/Office%20365/Outlook/Kanban%20board/js/app.js:27:9)
   at fn (Function code:2:180)
   at Scope.prototype.$eval (file:///C:/Users/MOSAI/OneDrive%20-%20H%20&%20M%20HENNES%20&%20MAURITZ%20AB/1.WORK/Shortcuts/Knowledge/Office%20365/Outlook/Kanban%20board/lib/angular.js:16554:9)
   at pre (file:///C:/Users/MOSAI/OneDrive%20-%20H%20&%20M%20HENNES%20&%20MAURITZ%20AB/1.WORK/Shortcuts/Knowledge/Office%20365/Outlook/Kanban%20board/lib/angular.js:25187:9)
   a

**Comment by evrenvarol** [comment]
In the config.js, what exactly you have configured for the BACKLOG_FOLDER item? Do you have the default settings?

**Comment by ghost** [comment]
Haven't done any changes to it. I have even just download the new file

![capture](https://cloud.githubusercontent.com/assets/22794016/19349506/a3ea3f88-9153-11e6-8f3d-3ad61a58280d.PNG)

**Comment by GrimmiMeloni** [comment]
I had exectly this problem. Also with IE 11.
@mobaraksaid - please check if the page is really treated as Intranet zone. In my case, it was not. You can do so, by right clicking on a blank spot in the page and selecting the properties (sorry, no zone indication in the status bar anymore since IE9 :-( )

@evrenvarol not sure why the MOTW did not work.

Anyways - I "fixed" this temporary by allowing the settings for the Internet Zone. It was sufficient in my case to allow the ActiveX with a Prompt. Not really fitting for daily use (or frequent reopens), but it allowed me to do the required debugging for the issue I previously reported.

**Comment by evrenvarol** [comment]
MOTW sets the kanban-ie.html to be loaded in Local Intranet Zone. 

I can replicate the exact issue (no tasks populating in IE) and the exact error message in the console, when the IE-> Local Intranet Zone -> Custom Level -> Initialize and script ActiveX controls not marked as safe for scripting is disabled.  (Local Intranet Zone on my machine is set to Medium-Low which is the default level )

When the option is enabled, tasks are populating perfectly fine. You may have some company-level AD GPOs pushing this option back to disabled, obviously we cannot do anything about that. 

I don't use IE view in my daily use either, I have only added it as couple of people asked whether that's possible to add. I usually suggest people to open the Taskboard folder in a new window if they want to see the board on a separate window. (Right click -> Open in a new window) This might be useful for people using multiple monitors.

**Comment by ghost** [comment]
I check the page zone and it was not local intranet zone. I will check my GPOs.
