### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by ghost** [evrenvarol/outlook-taskboard#5]
When i open any of the two .html files in either sublime or notepad++ and save it. The buttons are there, but the icons aren't shown, means i can still click on them. at least in outlook. If i open it in notepad it doesn't happen. I have tried to save with specific encodings like UTF-8 or ISO8859-1, but that doesn't help

![capture](https://cloud.githubusercontent.com/assets/22794016/19347802/fd6d466c-914a-11e6-95d9-2fda19200bc0.PNG)

**Comment by evrenvarol** [comment]
I use Sublime and all files are saved as "UTF-8" with Windows line endings. I've never had any similar issues.

When you edit those files, are you changing anything in them?

**Comment by ghost** [comment]
no, 
if I just make a space on a new line, just to indicate a change and save it.

**Comment by ghost** [comment]
It does show other changes that i make and save, but no matter what i do, i have to overwrite the file with the org. even undoing and saving does make any different.

**Comment by ghost** [comment]
I tried it on my other PC and no problems, so most be locally on my PC.
