### ISSUE TITLE
Using with Outlook Web App possible?

### ISSUE THREAD

**Issue by tobizimmi** [evrenvarol/outlook-taskboard#50]
Hello,
is it also possible to use this Outlook taskboard with the Outlook Web App?? Because if you're on Business trip with a IPad i think it's not working because there is no normal Outlook on an IPad.
Thanks for the Information.

Kind Regards

**Comment by evrenvarol** [comment]
Hi, 

Unfortunately, OWA does not support any customisation or add-ons. So this won't work on any mobile devices. 

If your Microsoft Exchange allows you to sync with mobile devices, you can use Reminders app to manage your tasks. As Outlook Taskboard uses task folders, you can see your tasks in individual folders (e.g. NEXT, FOCUS, etc. ) and manage them via Reminders app.  It is not great, but it is something.
