### ISSUE TITLE
Deleting Task via its ribbon "delete" button leaves Taskboard out of sync

### ISSUE THREAD

**Issue by GrimmiMeloni** [evrenvarol/outlook-taskboard#6]
Hi,
I just noticed, that when a task is opened (in a separate window), and I use the "Delete" button in the ribbon on that task, then the taskboard will not reflect that change.

Further interacting with the stale item on the taskboard, will lead to scripting errors.

**Comment by evrenvarol** [comment]
Normally, if you double click on a task or click on the edit task button, it opens the task in a separate window. If you save the task, the taskboard automatically reloads itself to reflect changes. 

I have just updated the app.js file to do same when you delete the task as well. So if you open the task within the taskboard and delete the task from the task window, the taskboard will reload itself and the deleted task will disappear. 

Unfortunately, the taskboard wouldn't reload itself, if you open the task directly from your Tasks folder or To Do list pane. So if you delete a task directly from Outlook Tasks folder or To-do, just refresh the taskboard screen by pressing the Refresh button or F5 key. 

Hope this helps. I'm closing this issue, please update your app.js file and let me know if the issue still remains.
